<?php {
	/* INITIALIZING GLOBAL VARIABLES FOR CUSTOMERS & COOKIES, SETS VALUE FROM ajax_cookie.php page */
	$customer='0'; $cookid='0'; $newuser='1'; 
	/* CONNECTING DATABASE */
	include 'db_connect.php';
    /* CHECKING COOKIE & SET NEW IF NOT FOUND IN BROWSER */	
	include 'ajax_cookie.php'; 
	/* FOR CREATING SEO FRIENDLY URLS */	
	include_once('make_url.php'); ?>
<?php
/*
+++++++++++++++++++++++++  DOCUMENTATION / README V1.0 +++++++++++++++++++++++++++++++++

************ BUIILD TECHNOLOGIES ************
* FRONT END: BULMA CSS 0.94                 *
* JS DEPENDENCY: JQUERY 3.6.0               *
* BACKEND: PHP 8.3 (raw)+ MYSQLI            *
* lOCAL DEVELOPMENT: XAMPP LATEST (V.3.3.0) *
*********************************************

***************** WEBSITE'S FOLDER STRUCTURE *********************
ASSETS    -> CONTAINS CSS, JS, IMAGES FILES REQUIRED FOR WEBSITE
BILL      -> CONTAINS CSS, JS FOR INVOICE GENERATION
PHPQRCODE -> CONTAINS LIBRARY FOR QR CODE GENERATION IN INVOICE
QRIMAGES  -> STORES ALL QR CODES GENERATED FROM INVOICES
WFS       -> CONTENT MANAGEMENT SYSTEM FOLDER
PS: REST FOLDERS ARE AUTOGENERATED BY THE CPANEL
******************************************************************

++++++++++++++++++++++ PLUGINS / TOOLS INSTALLED +++++++++++++++++++++++++
1. BOOTSTRAP TYPEHEAD.JS https://twitter.github.io/typeahead.js/examples/
2. QR CODE ENCODER https://github.com/Darkflib/php-qrcode/tree/master 
3. OWL CAROUSEL https://github.com/OwlCarousel2/OwlCarousel2 
4. Tawk.to FOR LIVE CHAT https://www.tawk.to/  
5. SMS otp service sparrow API https://sparrowsms.com/     
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

***************** DEVELOPER'S NOTE *********************************************************************************************
1. VVI= WHEN RELOCATING TO ANY NEW SERVER IN FUTURE, DON'T FORGET TO ENABLE GD LIBRARY INSIDE PHP IN THE SERVER, 
   IT WILL CAUSE ISSUES WITH IMAGE UPLOAD & QR CODE GENERATION.
2. WEBSITE IS DIVIDED INTO HEADER, BODY AND FOOTER SECTION; HEADER & FOOTER IN SEPERATE PHP FILES. (header.php & footer.php)
3. EVERY MODAL JS INTERACTIONS IS CODED IN JS.PHP FILE
4. ALL CUSTOM CSS MADE FOR WEBSITE STORED IN : assets/css/css.css (FILE)
5. All SEO-FRIENDLY URLS ARE ROUTED THROUGH .HTACCESS FILE, ALSO DESTINATION URLS IN SOME AJAX CALLS ARE ROUTED VIA .HTACCESS
6. DON'T DELETE THIS DOCUMENTATION FROM CODE, ADD ON THIS DOCUMENTATION WHEN A NEW UPDATE IS MADE & UPDATE VERSION TOO 
********************************************************************************************************************************

++++++++++++++++++++++++++ DOCUMENTATION / README V1.0 +++++++++++++++++++++++++++++
*/
 ?>
<!DOCTYPE html>
<html lang="en">
<head>
 <meta http-equiv="Cache-control" content="public">
 <meta charset="utf-8">
 <meta name="viewport" content="width=device-width, initial-scale=1">
 <title>White Feather's Jewellery</title>
 <meta name="viewport" content="width=device-width, initial-scale=1">
 <?PHP /* LOADING REQUIRED CSS */ ?>
 <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
 <link rel="stylesheet" href="assets/owl/owl.carousel.min.css">
 <link rel="stylesheet" href="assets/owl/owl.theme.default.min.css">
 <link rel="stylesheet" href="assets/css/css.css">
 <script src="https://cdnjs.cloudflare.com/ajax/libs/qrcodejs/1.0.0/qrcode.min.js" integrity="sha512-CNgIRecGo7nphbeZ04Sc13ka07paqdeTu0WR1IM4kNcpmBAUSHSQX0FslNhTDadL4O5SAGapGt4FodqL8My0mA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
 <?PHP /* END => LOADING REQUIRED CSS */ ?>
 <link rel="icon" type="image/x-icon" href="assets/images/favicon.ico">
 <style id="antiClickjack">
    body{display:none !important;}
</style>

<!-- clickjacking prevention -->
<script type="text/javascript">
    if (self === top) {
        var antiClickjack = document.getElementById("antiClickjack");
		var intruder = document.getElementById("intruder");
        antiClickjack.parentNode.removeChild(antiClickjack);
    } else {
        top.location = self.location;
    }
</script>
</head>

<body style="letter-spacing:0.02em;">
	<div id="loader" class="center">
	</div>
    
<?php /* CONTAINS MENU */ include('header.php'); ?>

<?PHP /*-- BODY SECTION START --*/?>

<?php 

      $sqlslt = "Select * from `whitefeat_wf_new`.`video` where visible='1' ORDER BY RAND() LIMIT 1"; 
      $displayslt=mysqli_query($con,$sqlslt);
	  $countslt=mysqli_num_rows($displayslt);
	  $rowslt=mysqli_fetch_array($displayslt);
	  
 
echo '<div class="slider slider-spacing">
  <div class="slide_viewer">
    <div class="slide_group">';
	
	  $sqlslt = "Select * from `whitefeat_wf_new`.`slider` where visible='1' ORDER BY s_order "; 
      $displayslt=mysqli_query($con,$sqlslt);
	  while($rowslt=mysqli_fetch_array($displayslt))
	  {      
      echo'
	  <div class="slide">
	    <a href="'; 
		$target='#';
		if($rowslt['hyper_link']!=''){$target=$rowslt['hyper_link'];}
		if($rowslt['category_link']!=0){$target='products/'; 
	       $sqlslt2 = "Select * from `whitefeat_wf_new`.`package_category` where cat_id='".$rowslt['category_link']."'"; 
           $displayslt2=mysqli_query($con,$sqlslt2);
	       $rowslt2=mysqli_fetch_array($displayslt2);
    	   $target=$target.make_url($rowslt2['cat_name']);
		}
		if($rowslt['package_link']!=0){
		   $sqlslt2 = "Select * from `whitefeat_wf_new`.`package` where id_pack='".$rowslt['package_link']."'"; 
           $displayslt2=mysqli_query($con,$sqlslt2);
	       $rowslt2=mysqli_fetch_array($displayslt2);
    	   $target=make_url($rowslt2['p_name']);	
		}
		
		echo $target.'"><img src="assets/images/slider/'.$rowslt['s_path'].'" class="slide-img"/></a>
      </div>';


	echo' 
      
    </div>
  </div>
</div>

<div class="slide_buttons" >
</div>

<div class="directional_nav">
  <div class="previous_btn" title="Previous">
    <i class="fa fa-arrow-alt-circle-left"></i>    
  </div>
  <div class="next_btn" title="Next">
    <i class="fa fa-arrow-alt-circle-right"></i>
  </div>
</div><!-- End // .directional_nav -->';
	  
	  
	  }

/* HOMEPAGE SLIDER END */ ?>


	

<?PHP /* 3 COLLAGE SECTION START (BANNER SET 1) */ ?>
<div class="container is-fluid">
 <div class="columns">
    
	
	<?php
      $sqlb1 = "Select * from `whitefeat_wf_new`.`banner1` where visible='1' ORDER BY s_order "; 
      $displayb1=mysqli_query($con,$sqlb1); $sn=1;
	  while($rowb1=mysqli_fetch_array($displayb1))
	  {
         if($sn==1){		  
         echo'
		 <div class="column is-6"> 
        <a href="';
		
        $target='#';
		if($rowb1['hyper_link']!=''){$target=$rowb1['hyper_link'];}
		if($rowb1['title_link']!=0){$target='products/'; 
	       $sqlslt2 = "Select * from `whitefeat_wf_new`.`package_category` where cat_id='".$rowb1['title_link']."'"; 
           $displayslt2=mysqli_query($con,$sqlslt2);
	       $rowslt2=mysqli_fetch_array($displayslt2);
    	   $target=$target.make_url($rowslt2['cat_name']);
		}
		if($rowb1['package_link']!=0){
		   $sqlslt2 = "Select * from `whitefeat_wf_new`.`package` where id_pack='".$rowb1['package_link']."'"; 
           $displayslt2=mysqli_query($con,$sqlslt2);
	       $rowslt2=mysqli_fetch_array($displayslt2);
    	   $target=make_url($rowslt2['p_name']);	
		}

		echo $target.'"><img src="assets/images/banner1/'.$rowb1['s_path'].'" class="image is-fullwidth m-img" style="height:600px; object-fit: cover;"></a>
        </div>';
		}
		
		if($sn==2){
	  echo'
   <div class="column is-6">
    <div class="column is-12 p-0" class="image is-fullwidth" style="margin-bottom:3%;" >
	 <a href="';
		
        $target='#';
		if($rowb1['hyper_link']!=''){$target=$rowb1['hyper_link'];}
		if($rowb1['title_link']!=0){$target='products/'; 
	       $sqlslt2 = "Select * from `whitefeat_wf_new`.`package_category` where cat_id='".$rowb1['title_link']."'"; 
           $displayslt2=mysqli_query($con,$sqlslt2);
	       $rowslt2=mysqli_fetch_array($displayslt2);
    	   $target=$target.make_url($rowslt2['cat_name']);
		}
		if($rowb1['package_link']!=0){
		   $sqlslt2 = "Select * from `whitefeat_wf_new`.`package` where id_pack='".$rowb1['package_link']."'"; 
           $displayslt2=mysqli_query($con,$sqlslt2);
	       $rowslt2=mysqli_fetch_array($displayslt2);
    	   $target=make_url($rowslt2['p_name']);	
		}

		echo $target.'"><img src="assets/images/banner1/'.$rowb1['s_path'].'" style="width:100%; height:290px; object-fit:cover; "></a>
		</div>';
		}
		
		if($sn==3){
    echo'<div class="column is-12 p-0">
	 <a href="';
		
        $target='#';
		if($rowb1['hyper_link']!=''){$target=$rowb1['hyper_link'];}
		if($rowb1['title_link']!=0){$target='products/'; 
	       $sqlslt2 = "Select * from `whitefeat_wf_new`.`package_category` where cat_id='".$rowb1['title_link']."'"; 
           $displayslt2=mysqli_query($con,$sqlslt2);
	       $rowslt2=mysqli_fetch_array($displayslt2);
    	   $target=$target.make_url($rowslt2['cat_name']);
		}
		if($rowb1['package_link']!=0){
		   $sqlslt2 = "Select * from `whitefeat_wf_new`.`package` where id_pack='".$rowb1['package_link']."'"; 
           $displayslt2=mysqli_query($con,$sqlslt2);
	       $rowslt2=mysqli_fetch_array($displayslt2);
    	   $target=make_url($rowslt2['p_name']);	
		}

		echo $target.'"><img src="assets/images/banner1/'.$rowb1['s_path'].'"  class="image is-fullwidth" style="width:100%; object-fit:cover;height:290px;" ></a>
	</div>
   </div>';
                }
        
		$sn++;
	  }


	?>
 
 </div>

</div>

<?PHP /* 3 COLLAGE SECTION END (BANNER SET 1)  */ ?>







<?PHP /* 6 MINI COLLAGE SECTION START (BANNER SET 2) */ ?>

<div class="container is-fluid banner2" style=" margin-top:1%;">
 <div class="columns is-mobile is-multiline">
 
     <?php 
	 
	  $sqlb1 = "Select * from `whitefeat_wf_new`.`banner2` where visible='1' ORDER BY s_order "; 
      $displayb1=mysqli_query($con,$sqlb1); $sn=1;
	  while($rowb1=mysqli_fetch_array($displayb1))
	  {
	  
	    if($sn==1){
			echo'<div class="column is-12-mobile is-4-desktop is-2-tablet">
       <a href="';
		
        $target='#';
		if($rowb1['hyper_link']!=''){$target=$rowb1['hyper_link'];}
		if($rowb1['title_link']!=0){$target='products/'; 
	       $sqlslt2 = "Select * from `whitefeat_wf_new`.`package_category` where cat_id='".$rowb1['title_link']."'"; 
           $displayslt2=mysqli_query($con,$sqlslt2);
	       $rowslt2=mysqli_fetch_array($displayslt2);
    	   $target=$target.make_url($rowslt2['cat_name']);
		}
		if($rowb1['package_link']!=0){
		   $sqlslt2 = "Select * from `whitefeat_wf_new`.`package` where id_pack='".$rowb1['package_link']."'"; 
           $displayslt2=mysqli_query($con,$sqlslt2);
	       $rowslt2=mysqli_fetch_array($displayslt2);
    	   $target=make_url($rowslt2['p_name']);	
		}

		echo $target.'"><img src="assets/images/banner2/'.$rowb1['s_path'].'" class="image is-fullwidth banner-scale small-banner" style="max-height:240px;"></a>
      </div>
	  ';
		}
		
		if($sn==2){
		echo'
      <div class="column is-12-mobile is-4-desktop is-2-tablet">
       <a href="';
		
        $target='#';
		if($rowb1['hyper_link']!=''){$target=$rowb1['hyper_link'];}
		if($rowb1['title_link']!=0){$target='products/'; 
	       $sqlslt2 = "Select * from `whitefeat_wf_new`.`package_category` where cat_id='".$rowb1['title_link']."'"; 
           $displayslt2=mysqli_query($con,$sqlslt2);
	       $rowslt2=mysqli_fetch_array($displayslt2);
    	   $target=$target.make_url($rowslt2['cat_name']);
		}
		if($rowb1['package_link']!=0){
		   $sqlslt2 = "Select * from `whitefeat_wf_new`.`package` where id_pack='".$rowb1['package_link']."'"; 
           $displayslt2=mysqli_query($con,$sqlslt2);
	       $rowslt2=mysqli_fetch_array($displayslt2);
    	   $target=make_url($rowslt2['p_name']);	
		}

		echo $target.'"><img src="assets/images/banner2/'.$rowb1['s_path'].'" class="image is-fullwidth banner-scale small-banner" style="max-height:;"></a>
      </div>
	  ';}
	  
	   if($sn==3){
		   echo'<div class="column is-12-mobile is-4-desktop is-2-tablet">
       <a href="';
		
        $target='#';
		if($rowb1['hyper_link']!=''){$target=$rowb1['hyper_link'];}
		if($rowb1['title_link']!=0){$target='products/'; 
	       $sqlslt2 = "Select * from `whitefeat_wf_new`.`package_category` where cat_id='".$rowb1['title_link']."'"; 
           $displayslt2=mysqli_query($con,$sqlslt2);
	       $rowslt2=mysqli_fetch_array($displayslt2);
    	   $target=$target.make_url($rowslt2['cat_name']);
		}
		if($rowb1['package_link']!=0){
		   $sqlslt2 = "Select * from `whitefeat_wf_new`.`package` where id_pack='".$rowb1['package_link']."'"; 
           $displayslt2=mysqli_query($con,$sqlslt2);
	       $rowslt2=mysqli_fetch_array($displayslt2);
    	   $target=make_url($rowslt2['p_name']);	
		}

		echo $target.'"><img src="assets/images/banner2/'.$rowb1['s_path'].'" class="image is-fullwidth banner-scale small-banner" style="max-height:;"></a>
      </div>';
	   }
	   
	   if($sn==4){
		   echo' <div class="column is-12-mobile is-4-desktop is-2-tablet">
       <a href="';
		
        $target='#';
		if($rowb1['hyper_link']!=''){$target=$rowb1['hyper_link'];}
		if($rowb1['title_link']!=0){$target='products/'; 
	       $sqlslt2 = "Select * from `whitefeat_wf_new`.`package_category` where cat_id='".$rowb1['title_link']."'"; 
           $displayslt2=mysqli_query($con,$sqlslt2);
	       $rowslt2=mysqli_fetch_array($displayslt2);
    	   $target=$target.make_url($rowslt2['cat_name']);
		}
		if($rowb1['package_link']!=0){
		   $sqlslt2 = "Select * from `whitefeat_wf_new`.`package` where id_pack='".$rowb1['package_link']."'"; 
           $displayslt2=mysqli_query($con,$sqlslt2);
	       $rowslt2=mysqli_fetch_array($displayslt2);
    	   $target=make_url($rowslt2['p_name']);	
		}

		echo $target.'"><img src="assets/images/banner2/'.$rowb1['s_path'].'" class="image is-fullwidth banner-scale small-banner" style="max-height:;"></a>
      </div>';
	   }
	   
	   if($sn==5){
		   echo'<div class="column is-12-mobile is-4-desktop is-2-tablet">
       <a href="';
		
        $target='#';
		if($rowb1['hyper_link']!=''){$target=$rowb1['hyper_link'];}
		if($rowb1['title_link']!=0){$target='products/'; 
	       $sqlslt2 = "Select * from `whitefeat_wf_new`.`package_category` where cat_id='".$rowb1['title_link']."'"; 
           $displayslt2=mysqli_query($con,$sqlslt2);
	       $rowslt2=mysqli_fetch_array($displayslt2);
    	   $target=$target.make_url($rowslt2['cat_name']);
		}
		if($rowb1['package_link']!=0){
		   $sqlslt2 = "Select * from `whitefeat_wf_new`.`package` where id_pack='".$rowb1['package_link']."'"; 
           $displayslt2=mysqli_query($con,$sqlslt2);
	       $rowslt2=mysqli_fetch_array($displayslt2);
    	   $target=make_url($rowslt2['p_name']);	
		}

		echo $target.'"><img src="assets/images/banner2/'.$rowb1['s_path'].'" class="image is-fullwidth banner-scale small-banner" style="max-height:;"></a>
      </div>';}
	   
	   if($sn==6){
		   echo'<div class="column is-12-mobile is-4-desktop is-2-tablet">
       <a href="';
		
        $target='#';
		if($rowb1['hyper_link']!=''){$target=$rowb1['hyper_link'];}
		if($rowb1['title_link']!=0){$target='products/'; 
	       $sqlslt2 = "Select * from `whitefeat_wf_new`.`package_category` where cat_id='".$rowb1['title_link']."'"; 
           $displayslt2=mysqli_query($con,$sqlslt2);
	       $rowslt2=mysqli_fetch_array($displayslt2);
    	   $target=$target.make_url($rowslt2['cat_name']);
		}
		if($rowb1['package_link']!=0){
		   $sqlslt2 = "Select * from `whitefeat_wf_new`.`package` where id_pack='".$rowb1['package_link']."'"; 
           $displayslt2=mysqli_query($con,$sqlslt2);
	       $rowslt2=mysqli_fetch_array($displayslt2);
    	   $target=make_url($rowslt2['p_name']);	
		}

		echo $target.'"><img src="assets/images/banner2/'.$rowb1['s_path'].'" class="image is-fullwidth banner-scale small-banner" style="max-height:;"></a>
      </div>';
	   }
	  
	  
	  
		
		$sn++;
	  }
	 
	 ?>
 </div>
</div>

<?PHP /* 6 MINI COLLAGE SECTION END (BANNER SET 2) */ ?>





<?PHP /* 3 COLLECTION TAG FEATURE AREA START */ ?>

<div class="container is-fluid top-div-banner">
<div class="columns is-mobile 3div-banner">
<?php 

      $sqlb1 = "Select * from `whitefeat_wf_new`.`package_collection`  ORDER BY pc_id limit 3 "; 
      $displayb1=mysqli_query($con,$sqlb1); $sn=1;
	  while($rowb1=mysqli_fetch_array($displayb1))
	  {
		  $url=make_url($rowb1['pc_name']);
		  echo'
		   <div class="column is-6-mobile '; 
           if($sn==2){echo'has-text-centered top-div';}
		   echo'">
<div class="banner">
    <div class="banner__image-container">
        <a href="collection/'.$url;
		
        

		echo '"><img class="banner__image" src="assets/images/collection/'.$rowb1['pc_image'].'"/></a>
    </div>
</div>';

if($sn==2){
echo'
<br>
<a href="jewellerycollection"><button class="button is-info is-light">View All Collections</button></a>';
}

echo'</div>
		  
		  ';
		  $sn++;
		  
	  }

?>

</div>
</div>

<?PHP /* 3 COLLECTION TAG FEATURE AREA END */ ?>






<?PHP /* 4 COLLAGE SECTION START (BANNER SET 3) */ ?>

<div class="container is-fluid">
 <?php 
	 
	  $sqlb1 = "Select * from `whitefeat_wf_new`.`banner4` where visible='1' ORDER BY s_order limit 4"; 
      $displayb1=mysqli_query($con,$sqlb1); $sn=1;
	  while($rowb1=mysqli_fetch_array($displayb1))
	  {
	  
	    if($sn==1){echo'
		<div class="columns">
   <div class="column " >
    <a href="';
		
        $target='#';
		if($rowb1['hyper_link']!=''){$target=$rowb1['hyper_link'];}
		if($rowb1['title_link']!=0){$target='products/'; 
	       $sqlslt2 = "Select * from `whitefeat_wf_new`.`package_category` where cat_id='".$rowb1['title_link']."'"; 
           $displayslt2=mysqli_query($con,$sqlslt2);
	       $rowslt2=mysqli_fetch_array($displayslt2);
    	   $target=$target.make_url($rowslt2['cat_name']);
		}
		if($rowb1['package_link']!=0){
		   $sqlslt2 = "Select * from `whitefeat_wf_new`.`package` where id_pack='".$rowb1['package_link']."'"; 
           $displayslt2=mysqli_query($con,$sqlslt2);
	       $rowslt2=mysqli_fetch_array($displayslt2);
    	   $target=make_url($rowslt2['p_name']);	
		}

		echo $target.'"><img src="assets/images/banner4/'.$rowb1['s_path'].'" style="width:100%;"/></a>
   </div>
		';}
 
	    if($sn==2){
			echo'<div class="column " >
    <a href="';
		
        $target='#';
		if($rowb1['hyper_link']!=''){$target=$rowb1['hyper_link'];}
		if($rowb1['title_link']!=0){$target='products/'; 
	       $sqlslt2 = "Select * from `whitefeat_wf_new`.`package_category` where cat_id='".$rowb1['title_link']."'"; 
           $displayslt2=mysqli_query($con,$sqlslt2);
	       $rowslt2=mysqli_fetch_array($displayslt2);
    	   $target=$target.make_url($rowslt2['cat_name']);
		}
		if($rowb1['package_link']!=0){
		   $sqlslt2 = "Select * from `whitefeat_wf_new`.`package` where id_pack='".$rowb1['package_link']."'"; 
           $displayslt2=mysqli_query($con,$sqlslt2);
	       $rowslt2=mysqli_fetch_array($displayslt2);
    	   $target=make_url($rowslt2['p_name']);	
		}

		echo $target.'"><img src="assets/images/banner4/'.$rowb1['s_path'].'" style="width:100%;"/></a>
   </div>
 </div> ';
		}
 
	    if($sn==3){
			
			echo' <div class="columns">
   <div class="column " >
    <a href="';
		
        $target='#';
		if($rowb1['hyper_link']!=''){$target=$rowb1['hyper_link'];}
		if($rowb1['title_link']!=0){$target='products/'; 
	       $sqlslt2 = "Select * from `whitefeat_wf_new`.`package_category` where cat_id='".$rowb1['title_link']."'"; 
           $displayslt2=mysqli_query($con,$sqlslt2);
	       $rowslt2=mysqli_fetch_array($displayslt2);
    	   $target=$target.make_url($rowslt2['cat_name']);
		}
		if($rowb1['package_link']!=0){
		   $sqlslt2 = "Select * from `whitefeat_wf_new`.`package` where id_pack='".$rowb1['package_link']."'"; 
           $displayslt2=mysqli_query($con,$sqlslt2);
	       $rowslt2=mysqli_fetch_array($displayslt2);
    	   $target=make_url($rowslt2['p_name']);	
		}

		echo $target.'"><img src="assets/images/banner4/'.$rowb1['s_path'].'" style="width:100%;"/></a>
   </div>
   ';
		}
 
	    if($sn==4){
			
			echo'<div class="column " >
    <a href="';
		
        $target='#';
		if($rowb1['hyper_link']!=''){$target=$rowb1['hyper_link'];}
		if($rowb1['title_link']!=0){$target='products/'; 
	       $sqlslt2 = "Select * from `whitefeat_wf_new`.`package_category` where cat_id='".$rowb1['title_link']."'"; 
           $displayslt2=mysqli_query($con,$sqlslt2);
	       $rowslt2=mysqli_fetch_array($displayslt2);
    	   $target=$target.make_url($rowslt2['cat_name']);
		}
		if($rowb1['package_link']!=0){
		   $sqlslt2 = "Select * from `whitefeat_wf_new`.`package` where id_pack='".$rowb1['package_link']."'"; 
           $displayslt2=mysqli_query($con,$sqlslt2);
	       $rowslt2=mysqli_fetch_array($displayslt2);
    	   $target=make_url($rowslt2['p_name']);	
		}

		echo $target.'"><img src="assets/images/banner4/'.$rowb1['s_path'].'" style="width:100%;"/></a>
   </div>
 </div>';
		}
 
     $sn++;
	  }
 
 ?>

</div>

<?PHP /* 4 COLLAGE SECTION END (BANNER SET 3) */ ?>












<?PHP /* APPOINMENT + ADDRESS COLLAGE START  */ ?>

<div class="container is-fluid" style="margin-top:1.5em; background-color:#F9F9FA; padding-top:2em; padding-bottom:2em;">
 <div class="columns">
 
   <?PHP /* APPOINMENT IMAGE SECTION START  */ ?>
   <div class="column">
    
	<div class="columns">
	    <div class="column is-8">
          <img src="assets/images/extra/pickup.jpg" style=" width:100%;"/>
		</div>
		<div class="column is-6 banner-trail" style="margin-left:-15%; padding-top:15%;">
          <h2 class="subtitle"><span  class="p-2" style="background:rgba(0,0,0,0.5); color:#fff;">Not Sure Which Design To Pick?</span></h2>
		  
          <h2 style="margin-top:-0.9em;"><small class=" p-1" style="background:rgba(255,255,255,0.5); color:#000;">Book A FREE Home Trial!</small></h2>
		  
		  
		  

	   <br>
	   <button class="button is-info appointment-button" style="margin-top:0.5em;" data-target="modal-ter2"><i class="fas fa-calendar-alt"></i>&nbsp; Schedule Appointment</button>
	   
	   
	   <?PHP /* APPOINMENT FORM MODAL START  */ ?>
	     <div class="modal" id="modal-ter2">
  <div class="modal-background"></div>
  <div class="modal-card">
    <header class="modal-card-head" style="background: rgb(241,243,244);
background: linear-gradient(90deg, rgba(241,243,244,1) 0%, rgba(226,225,219,1) 34%, rgba(80,225,255,1) 80%, rgba(116,228,250,1) 98%);">
      <p class="modal-card-title"><i class="fas fa-house-user"></i> Home Appointment Form</p>
      <button class="delete" aria-label="close"></button>
    </header>
    <section class="modal-card-body">
      
	 

<?php 

	    if($GLOBALS['customer']==0){
	  echo'<div class="field">
  <label class="label">Name <span class="has-text-danger">*</span>
</label>
  <div class="control">
  <div class="control has-icons-left has-icons-right">
    <input class="input home_name" type="text" placeholder="Your Full Name">
	<span class="icon is-small is-left">
      <i class="fas fa-user"></i>
    </span>
	</div>
  </div>
</div>

<div class="field">
  <label class="label">Full Address <span class="has-text-danger">*</span></label>
  <div class="control has-icons-left has-icons-right">
    <input class="input home_add" type="text" placeholder="Your Full Address" value="">
    <span class="icon is-small is-left">
      <i class="fas fa-map-marker"></i>
    </span>
    
  </div>
</div>

<div class="field">
  <label class="label">Contact number <span class="has-text-danger">*</span></label>
  <div class="control has-icons-left has-icons-right">
    <input class="input home_phone" type="text" placeholder="+97798XXXXXXXX" value="">
    <span class="icon is-small is-left">
      <i class="fas fa-mobile"></i>
    </span>
    
  </div>
</div>';

        }

?>



<div class="field">
  <label class="label">Message <small class="is-size-7"></small></label>
  <div class="control">
    <textarea class="textarea home_msg" placeholder="Please Write Jewelleries you want to try..."></textarea>
  </div>
</div>

<div class="field">
  <div class="control">
    <label class="checkbox">
      
      <i class="fas fa-check-circle"></i> &nbsp;I agree to the <a href="#">terms and conditions</a>
    </label>
  </div>
</div>


<div class="field is-grouped mt-2">
  <div class="control">
    <button class="button is-info send_home_appoint">Submit</button>
  </div>
  <div class="control">
    <button class="button is-link is-light">Cancel</button>
  </div>
</div>
	  
    </section>
  </div>
</div>
           <?PHP /* APPOINMENT FORM MODAL END  */ ?>
	
	   
	   
	   
	   
		</div>
	</div>
	
   </div>
   <?PHP /* APPOINMENT IMAGE SECTION END  */ ?>   
   
      <?PHP /* SHOWROOM ADDRESS IMAGE START  */ ?>
   <div class="column">
    
	<div class="columns">
	    <div class="column is-8">
          <img src="assets/images/extra/store.jpg" style="width:100%;"/>
		</div>
		<div class="column is-6 banner-trail" style="margin-left:-15%; padding-top:15%;">
          <h2 class="subtitle"><strong class="p-2" style="background:rgba(0,0,0,0.5); color:#fff;">WHITE FEATHER'S STORE</strong></h2>
		  
	   <h2 style="margin-top:-0.9em;">
       <small class="p-1" style="background:rgba(255,255,255,0.5); color:#000;">Newroad, Kathmandu, Kichhapokhari</small>
	   </h2>
	   
	   <br><br>
	     <b class="is-info button is-disabled"><i class="fas fa-phone" style="text-shadow: 6px 6px 11px #CECECE;"></i> &nbsp;+977-01-5365343</b>
		</div>
	</div>
	
   </div>
       <?PHP /* SHOWROOM ADDRESS IMAGE END  */ ?>
 
 
 </div> 
</div>

<?PHP /* APPOINMENT + ADRESS COLLAGE END  */ ?>


<?PHP /*-- BODY SECTION END --*/ ?>


<?PHP /* JEQUERY LOAD  */ ?>
<script src="assets/js/jquery-3.6.0.min.js"></script>
<?PHP /* OWL CAROUSEL JS FILE LOAD  */ ?>
<script src="assets/owl/owl.carousel.min.js"></script>


<?php 
/* SHOWING COOKIE NOTICE FOR FIRST NEW WEBSITE VISITOR START */
if($newuser==1){
echo'<div class="notification is-info is-light is-fullwidth" style="position:fixed; z-index:1111; bottom:-25px; width:100%;">
  <button class="delete"></button>
  We use cookies to <strong>collect data</strong> for providing you better product viewing experience, by closing this dialog you accept with our <a href="#"><strong>content policy</strong></a>

</div>';
}
/* SHOWING COOKIE NOTICE FOR FIRST NEW WEBSITE VISITOR END */
?>

<?PHP /* COOKIE NOTIFICATION JS HANDLER START */ ?>
<script>
document.addEventListener('DOMContentLoaded', () => {
  (document.querySelectorAll('.notification .delete') || []).forEach(($delete) => {
    const $notification = $delete.parentNode;

    $delete.addEventListener('click', () => {
      $notification.parentNode.removeChild($notification);
    });
  });
});
</script>
<?PHP /* COOKIE NOTIFICATION JS HANDLER START */ ?>



<?php /* CONTAINS MENU */  include('footer.php'); ?>
<?php /* CONTAINS DEPENDENT JS FILES LINKS + SCRIPTS */  include('js.php'); ?>

</body>

</html>
<?php }?>