<?php {
	/* INITIALIZING GLOBAL VARIABLES FOR CUSTOMERS & COOKIES, SETS VALUE FROM ajax_cookie.php page */
	$customer = '0';
	$cookid = '0';
	$newuser = '1';
	/* CONNECTING DATABASE */
	include 'db_connect.php';
	/* CHECKING COOKIE & SET NEW IF NOT FOUND IN BROWSER */
	include 'ajax_cookie.php';
	/* FOR CREATING SEO FRIENDLY URLS */
	include_once('make_url.php'); ?>
	<?php
	/*
	+++++++++++++++++++++++++  DOCUMENTATION / README V1.0 +++++++++++++++++++++++++++++++++

	************ BUIILD TECHNOLOGIES ************
	* FRONT END: BULMA CSS 0.94                 *
	* JS DEPENDENCY: JQUERY 3.6.0               *
	* BACKEND: PHP 8.3 (raw)+ MYSQLI            *
	* lOCAL DEVELOPMENT: XAMPP LATEST (V.3.3.0) *
	*********************************************

	***************** WEBSITE'S FOLDER STRUCTURE *********************
	ASSETS    -> CONTAINS CSS, JS, IMAGES FILES REQUIRED FOR WEBSITE
	BILL      -> CONTAINS CSS, JS FOR INVOICE GENERATION
	PHPQRCODE -> CONTAINS LIBRARY FOR QR CODE GENERATION IN INVOICE
	QRIMAGES  -> STORES ALL QR CODES GENERATED FROM INVOICES
	WFS       -> CONTENT MANAGEMENT SYSTEM FOLDER
	PS: REST FOLDERS ARE AUTOGENERATED BY THE CPANEL
	******************************************************************

	++++++++++++++++++++++ PLUGINS / TOOLS INSTALLED +++++++++++++++++++++++++
	1. BOOTSTRAP TYPEHEAD.JS https://twitter.github.io/typeahead.js/examples/
	2. QR CODE ENCODER https://github.com/Darkflib/php-qrcode/tree/master 
	3. OWL CAROUSEL https://github.com/OwlCarousel2/OwlCarousel2 
	4. Tawk.to FOR LIVE CHAT https://www.tawk.to/  
	5. SMS otp service sparrow API https://sparrowsms.com/     
	++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

	***************** DEVELOPER'S NOTE *********************************************************************************************
	1. VVI= WHEN RELOCATING TO ANY NEW SERVER IN FUTURE, DON'T FORGET TO ENABLE GD LIBRARY INSIDE PHP IN THE SERVER, 
	   IT WILL CAUSE ISSUES WITH IMAGE UPLOAD & QR CODE GENERATION.
	2. WEBSITE IS DIVIDED INTO HEADER, BODY AND FOOTER SECTION; HEADER & FOOTER IN SEPERATE PHP FILES. (header.php & footer.php)
	3. EVERY MODAL JS INTERACTIONS IS CODED IN JS.PHP FILE
	4. ALL CUSTOM CSS MADE FOR WEBSITE STORED IN : assets/css/css.css (FILE)
	5. All SEO-FRIENDLY URLS ARE ROUTED THROUGH .HTACCESS FILE, ALSO DESTINATION URLS IN SOME AJAX CALLS ARE ROUTED VIA .HTACCESS
	6. DON'T DELETE THIS DOCUMENTATION FROM CODE, ADD ON THIS DOCUMENTATION WHEN A NEW UPDATE IS MADE & UPDATE VERSION TOO 
	********************************************************************************************************************************

	++++++++++++++++++++++++++ DOCUMENTATION / README V1.0 +++++++++++++++++++++++++++++
	*/
	?>
	<!DOCTYPE html>
	<html lang="en">

	<head>
		<meta http-equiv="Cache-control" content="public">
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>White Feather's Jewellery</title>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<?PHP /* LOADING REQUIRED CSS */ ?>
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
			integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA=="
			crossorigin="anonymous" referrerpolicy="no-referrer" />
		<link rel="stylesheet" href="assets/owl/owl.carousel.min.css">
		<link rel="stylesheet" href="assets/owl/owl.theme.default.min.css">
		<link rel="stylesheet" href="assets/css/css.css">
		<script src="https://cdnjs.cloudflare.com/ajax/libs/qrcodejs/1.0.0/qrcode.min.js"
			integrity="sha512-CNgIRecGo7nphbeZ04Sc13ka07paqdeTu0WR1IM4kNcpmBAUSHSQX0FslNhTDadL4O5SAGapGt4FodqL8My0mA=="
			crossorigin="anonymous" referrerpolicy="no-referrer"></script>
		<?PHP /* END => LOADING REQUIRED CSS */ ?>
		<link rel="icon" type="image/x-icon" href="https://whitefeatherbucket.s3.ap-south-1.amazonaws.com/product_images/home/favicon.ico">
	</head>

	<body style="letter-spacing:0.02em; visibility:hidden;">
		<div id="loader" class="center">
		</div>

		<?php /* CONTAINS MENU */ include('header.php'); ?>

		<?PHP /*-- BODY SECTION START --*/ ?>

		<?php

		$sqlslt = "Select * from `whitefeat_wf_new`.`video` where visible='1' ORDER BY RAND() LIMIT 1";
		$displayslt = mysqli_query($con, $sqlslt);
		$countslt = mysqli_num_rows($displayslt);
		$rowslt = mysqli_fetch_array($displayslt);


		echo '<div class="slider slider-spacing">
  <div class="slide_viewer">
    <div class="slide_group">';

		$sqlslt = "Select * from `whitefeat_wf_new`.`slider` where visible='1' ORDER BY s_order ";
		$displayslt = mysqli_query($con, $sqlslt);
		while ($rowslt = mysqli_fetch_array($displayslt)) {
			echo '
	  <div class="slide">
	    <a href="';
			$target = '#';
			if ($rowslt['hyper_link'] != '') {
				$target = $rowslt['hyper_link'];
			}
			if ($rowslt['category_link'] != 0) {
				$target = 'products/';
				$sqlslt2 = "Select * from `whitefeat_wf_new`.`package_category` where cat_id='" . $rowslt['category_link'] . "'";
				$displayslt2 = mysqli_query($con, $sqlslt2);
				$rowslt2 = mysqli_fetch_array($displayslt2);
				$target = $target . make_url($rowslt2['cat_name']);
			}
			if ($rowslt['package_link'] != 0) {
				$sqlslt2 = "Select * from `whitefeat_wf_new`.`package` where id_pack='" . $rowslt['package_link'] . "'";
				$displayslt2 = mysqli_query($con, $sqlslt2);
				$rowslt2 = mysqli_fetch_array($displayslt2);
				$target = make_url($rowslt2['p_name']);
			}

			echo $target . '"><img src="https://whitefeatherbucket.s3.ap-south-1.amazonaws.com/product_images/home/' . $rowslt['s_path'] . '" class="slide-img"/></a>
      </div>';


			echo ' 
      
    </div>
  </div>
</div>

<div class="slide_buttons" >
</div>

<div class="directional_nav">
  <div class="previous_btn" title="Previous">
    <i class="fa fa-arrow-alt-circle-left"></i>    
  </div>
  <div class="next_btn" title="Next">
    <i class="fa fa-arrow-alt-circle-right"></i>
  </div>
</div><!-- End // .directional_nav -->';


		}

		/* HOMEPAGE SLIDER END */ ?>
			<div class="container is-fluid" style="margin-top: 10px;">
				<a href="/gold-rate.php">
			<div class="card p-4" style="background: #01243a; color:white; overflow:hidden;">
				<div style="font-size:20px;font-weight:700;">Today's Gold and Silver Rates
					<hr style="margin-top:10px;background:#848482;height:1px;" />
				</div>
				<?php
				$sqlgol = "Select pm_id,price from `whitefeat_wf_new`.`package_material` where pm_id = 2";
				$gol = mysqli_query($con, $sqlgol);
				$gold = mysqli_fetch_array($gol);
				$sqlsil = "Select pm_id,price from `whitefeat_wf_new`.`package_material` where pm_id = 3";
				$sil = mysqli_query($con, $sqlsil);
				$silver = mysqli_fetch_array($sil);
				?>
				<div class="columns" style="padding-bottom:30px;">
					<div class="column" style="display:flex;align-items:center;justify-content:space-evenly;flex-wrap:wrap;">
						<div
							style="background-image:url(https://whitefeatherbucket.s3.ap-south-1.amazonaws.com/product_images/home/price_gold.webp);aspect-ratio:7/5;height:100px;object-fit:cover;background-size:cover;">
						</div>
						<div>
							<span style="color:#DAA520;font-size:18px;font-weight:700;">Gold</span> <br />
							<span style="color:#848482">Per Tola</span>
						</div>
						<div style="color:#DAA520;font-size:18px;font-weight:700;">
							RS. <?php echo $gold['price'] ?>
						</div>
					</div>
					<div class="column"
						style="display:flex;align-items:center;justify-content:space-evenly; border-left:0.5px solid #848482;flex-wrap:wrap;">
						<div
							style="background-image:url(https://whitefeatherbucket.s3.ap-south-1.amazonaws.com/product_images/home/price_silver.webp);aspect-ratio:6/5;height:100px;object-fit:cover;background-size:cover;">
						</div>
						<div>
							<span style="color:#c0c0c0;font-size:18px;font-weight:700;">Silver</span> <br />
							<span style="color:#848482">Per Tola</span>
						</div>
						<div style="color:#c0c0c0;font-size:18px;font-weight:700;margin-left:10px;">
							RS. <?php echo $silver['price'] ?>
						</div>
					</div>
				</div>
			</div>
		</a>
		</div>


		<div class="container is-fluid" style="margin-top: 20px;">
			<a href="/search.php?term=diamond%20pendant">
				<div class="columns" style="gap: 20px; margin: 10px auto;margin-bottom:30px;">
					<div class="column banner-scale"
						style="width:100%;aspect-ratio:5/7;overflow:hidden;background:url(https://whitefeatherbucket.s3.ap-south-1.amazonaws.com/product_images/home/IMG_8841.jpg);background-size:cover;object-position:center;margin-bottom:20px;">
					</div>
					<div class="column" style="display: flex;gap:20px; flex-direction: column;padding:0">
						<div class="banner-scale"
							style="width:100%;aspect-ratio:7/5 ;background:url(https://whitefeatherbucket.s3.ap-south-1.amazonaws.com/product_images/home/IMG_9153.jpg);background-size:cover;vertical-align:center;">
						</div>
						<div class="banner-scale"
							style="width:100%;aspect-ratio:7/5 ;background:url(https://whitefeatherbucket.s3.ap-south-1.amazonaws.com/product_images/home/1_11.jpg);background-size:cover;object-position:center;vertical-align:bottom;">
						</div>
					</div>
				</div>
			</a>
		</div>


		<div class="container is-fluid banner2" style=" margin:2% auto;">
			<div class="columns is-mobile is-multiline">
				<div class="column is-12-mobile is-4-desktop is-2-tablet">
					<a href="/products/engagement">
						<img src="https://whitefeatherbucket.s3.ap-south-1.amazonaws.com/product_images/home/e_r.png"
							class="image is-fullwidth banner-scale small-banner" style="max-height:240px;">
					</a>
				</div>
				<div class="column is-12-mobile is-4-desktop is-2-tablet">
					<a href="products/drops">
						<img src="https://whitefeatherbucket.s3.ap-south-1.amazonaws.com/product_images/home/ear.png"
							class="image is-fullwidth banner-scale small-banner" style="max-height:240px;">
					</a>
				</div>
				<div class="column is-12-mobile is-4-desktop is-2-tablet">
					<a href="/search.php?tags[]=gift">
						<img src="https://whitefeatherbucket.s3.ap-south-1.amazonaws.com/product_images/home/gift.png"
							class="image is-fullwidth banner-scale small-banner" style="max-height:240px;">
					</a>
				</div>
				<div class="column is-12-mobile is-4-desktop is-2-tablet">
					<a href="/products/flexible-bracelets">
						<img src="https://whitefeatherbucket.s3.ap-south-1.amazonaws.com/product_images/home/bracelet.png"
							class="image is-fullwidth banner-scale small-banner" style="max-height:240px;">
					</a>
				</div>
				<div class="column is-12-mobile is-4-desktop is-2-tablet">
					<a href="/products/gold-bangles">
						<img src="https://whitefeatherbucket.s3.ap-south-1.amazonaws.com/product_images/home/bangles.png"
							class="image is-fullwidth banner-scale small-banner" style="max-height:240px;">
					</a>
				</div>
				<div class="column is-12-mobile is-4-desktop is-2-tablet">
					<a href="/products/diamond-pendent">
						<img src="https://whitefeatherbucket.s3.ap-south-1.amazonaws.com/product_images/home/wed-jwel.png"
							class="image is-fullwidth banner-scale small-banner" style="max-height:240px;">
					</a>
				</div>
			</div>
		</div>
		<div class="container is-fluid"
			style="margin-top:1.5em; background-color:#F9F9FA; padding-top:2em; padding-bottom:2em;">
			<div class="columns" style="flex-wrap:wrap;justify-content:space-evenly;padding-top:10px;">
				<div class="column is-one-third"
					style="aspect-ratio:1/1 ;background:linear-gradient( transparent, 50%, rgba(0,0,0,0.8)),url(https://whitefeatherbucket.s3.ap-south-1.amazonaws.com/product_images/home/pickup.jpg);background-size:cover;object-position:top;position:relative;margin-bottom:20px;">
					<div
						style="position: absolute; padding-right: 20px;text-align:center;padding-left: 20px;padding-bottom:30px;height:100%;width:100%; display: flex;flex-direction:column;color:white;justify-content:flex-end;align-items:center;margin-left:-12px;">
						<div style="font-size:20px; font-weight: 700;text-align-center">
							Don't Know Which Design To Pick?
						</div>
						<div style="font-size:18px; font-weight: 400;">
							BOOK A FREE HOME TRIAL
						</div>
						<div class="cta">
							<button class="button primary" onclick="openModal('home-try-modal')">
								Book Appointment
							</button>
						</div>
					</div>
				</div>
				<div class="column is-one-third"
					style="aspect-ratio:1/1 ;background:linear-gradient( transparent, rgba(0,0,0,0.8)),url(https://whitefeatherbucket.s3.ap-south-1.amazonaws.com/product_images/home/store.jpg);background-size:cover;object-position:top;position:relative;margin-bottom:20px;">
					<div
						style="position: absolute; padding-right: 20px;text-align:center;padding-left: 20px;padding-bottom:30px;height:100%;width:100%; display: flex;flex-direction:column;color:white;justify-content:flex-end;align-items:center;margin-left:-12px;">
						<div style="font-size:20px; font-weight: 700;text-align-center">
							White Feathers Jewellery
						</div>
						<div style="font-size:18px; font-weight: 400;">
							New Road, Khichapokhari
						</div>
						<div class="cta">
							<a href="tel:+977-01-5365343">
								<button class="button primary">
									+977-01-5365343
								</button>
							</a>
						</div>
					</div>
				</div>
			</div>
		</div>

		<?PHP /*-- BODY SECTION END --*/ ?>


		<?PHP /* JEQUERY LOAD  */ ?>
		<script src="assets/js/jquery-3.6.0.min.js"></script>
		<?PHP /* OWL CAROUSEL JS FILE LOAD  */ ?>
		<script src="assets/owl/owl.carousel.min.js"></script>


		<?php
		/* SHOWING COOKIE NOTICE FOR FIRST NEW WEBSITE VISITOR START */
		if ($newuser == 1) {
			echo '<div class="notification is-info is-light is-fullwidth" style="position:fixed; z-index:1111; bottom:-25px; width:100%;">
  <button class="delete"></button>
  We use cookies to <strong>collect data</strong> for providing you better product viewing experience, by closing this dialog you accept with our <a href="#"><strong>content policy</strong></a>

</div>';
		}
		/* SHOWING COOKIE NOTICE FOR FIRST NEW WEBSITE VISITOR END */
		?>

		<?PHP /* COOKIE NOTIFICATION JS HANDLER START */ ?>
		<script>
			document.addEventListener('DOMContentLoaded', () => {
				(document.querySelectorAll('.notification .delete') || []).forEach(($delete) => {
					const $notification = $delete.parentNode;

					$delete.addEventListener('click', () => {
						$notification.parentNode.removeChild($notification);
					});
				});
			});
		</script>
		<?PHP /* COOKIE NOTIFICATION JS HANDLER START */ ?>



		<?php /* CONTAINS MENU */ include('footer.php'); ?>
		<?php /* CONTAINS DEPENDENT JS FILES LINKS + SCRIPTS */ include('js.php'); ?>

	</body>

	</html>
<?php } ?>